// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CTFerio.Ctfdcm
{
    /// <summary>
    /// CTFd is built around the Challenge resource, which contains all the attributes to define a part of the Capture The Flag event.
    /// 
    /// This implementation has support of On Demand infrastructures through [Chall-Manager](https://github.com/ctfer-io/chall-manager).
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Ctfd = CTFerio.Ctfd;
    /// using Ctfdcm = CTFerio.Ctfdcm;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var http = new Ctfdcm.ChallengeDynamicIaC("http", new()
    ///     {
    ///         Category = "misc",
    ///         Description = "...",
    ///         Value = 500,
    ///         Decay = 100,
    ///         Minimum = 50,
    ///         State = "visible",
    ///         Function = "logarithmic",
    ///         Shared = true,
    ///         DestroyOnFlag = true,
    ///         ManaCost = 1,
    ///         Scenario = "localhost:5000/some/scenario:v0.1.0",
    ///         Timeout = 600,
    ///         Topics = new[]
    ///         {
    ///             "Misc",
    ///         },
    ///         Tags = new[]
    ///         {
    ///             "misc",
    ///             "basic",
    ///         },
    ///     });
    /// 
    ///     var httpFlag = new Ctfd.Flag("httpFlag", new()
    ///     {
    ///         ChallengeId = http.Id,
    ///         Content = "CTF{some_flag}",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [CtfdcmResourceType("ctfdcm:index/challengeDynamicIaC:ChallengeDynamicIaC")]
    public partial class ChallengeDynamicIaC : global::Pulumi.CustomResource
    {
        /// <summary>
        /// An optional key=value map (both strings) to pass to the scenario.
        /// </summary>
        [Output("additional")]
        public Output<ImmutableDictionary<string, string>> Additional { get; private set; } = null!;

        /// <summary>
        /// Attribution to the creator(s) of the challenge.
        /// </summary>
        [Output("attribution")]
        public Output<string?> Attribution { get; private set; } = null!;

        /// <summary>
        /// Category of the challenge that CTFd groups by on the web UI.
        /// </summary>
        [Output("category")]
        public Output<string> Category { get; private set; } = null!;

        /// <summary>
        /// Connection Information to connect to the challenge instance, useful for pwn, web and infrastructure pentests.
        /// </summary>
        [Output("connectionInfo")]
        public Output<string> ConnectionInfo { get; private set; } = null!;

        /// <summary>
        /// The decay defines from each number of solves does the decay function triggers until reaching minimum. This function is defined by CTFd and could be configured through `.function`.
        /// </summary>
        [Output("decay")]
        public Output<int> Decay { get; private set; } = null!;

        /// <summary>
        /// Description of the challenge, consider using multiline descriptions for better style.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// Whether to destroy the instance once flagged.
        /// </summary>
        [Output("destroyOnFlag")]
        public Output<bool> DestroyOnFlag { get; private set; } = null!;

        /// <summary>
        /// Decay function to define how the challenge value evolve through solves, either linear or logarithmic.
        /// </summary>
        [Output("function")]
        public Output<string> Function { get; private set; } = null!;

        /// <summary>
        /// The flag validation logic.
        /// </summary>
        [Output("logic")]
        public Output<string> Logic { get; private set; } = null!;

        /// <summary>
        /// The cost (in mana) of the challenge once an instance is deployed.
        /// </summary>
        [Output("manaCost")]
        public Output<int> ManaCost { get; private set; } = null!;

        /// <summary>
        /// The number of instances after which not to pool anymore.
        /// </summary>
        [Output("max")]
        public Output<int> Max { get; private set; } = null!;

        /// <summary>
        /// Maximum amount of attempts before being unable to flag the challenge.
        /// </summary>
        [Output("maxAttempts")]
        public Output<int> MaxAttempts { get; private set; } = null!;

        /// <summary>
        /// The minimum number of instances to set in the pool.
        /// </summary>
        [Output("min")]
        public Output<int> Min { get; private set; } = null!;

        /// <summary>
        /// The minimum points for a dynamic-score challenge to reach with the decay function. Once there, no solve could have more value.
        /// </summary>
        [Output("minimum")]
        public Output<int> Minimum { get; private set; } = null!;

        /// <summary>
        /// Name of the challenge, displayed as it.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Suggestion for the end-user as next challenge to work on.
        /// </summary>
        [Output("next")]
        public Output<int?> Next { get; private set; } = null!;

        /// <summary>
        /// List of required challenges that needs to get flagged before this one being accessible. Useful for skill-trees-like strategy CTF.
        /// </summary>
        [Output("requirements")]
        public Output<Outputs.ChallengeDynamicIaCRequirements?> Requirements { get; private set; } = null!;

        /// <summary>
        /// The OCI reference to the scenario.
        /// </summary>
        [Output("scenario")]
        public Output<string> Scenario { get; private set; } = null!;

        /// <summary>
        /// Whether the instance will be shared between all players.
        /// </summary>
        [Output("shared")]
        public Output<bool> Shared { get; private set; } = null!;

        /// <summary>
        /// State of the challenge, either hidden or visible.
        /// </summary>
        [Output("state")]
        public Output<string> State { get; private set; } = null!;

        /// <summary>
        /// List of challenge tags that will be displayed to the end-user. You could use them to give some quick insights of what a challenge involves.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        /// <summary>
        /// The timeout (in seconds) after which the instance will be janitored.
        /// </summary>
        [Output("timeout")]
        public Output<int?> Timeout { get; private set; } = null!;

        /// <summary>
        /// List of challenge topics that are displayed to the administrators for maintenance and planification.
        /// </summary>
        [Output("topics")]
        public Output<ImmutableArray<string>> Topics { get; private set; } = null!;

        /// <summary>
        /// The date until the instance could run before being janitored.
        /// </summary>
        [Output("until")]
        public Output<string?> Until { get; private set; } = null!;

        /// <summary>
        /// The value (points) of the challenge once solved. It is mapped to `initial` under the hood, but displayed as `value` for consistency with the standard challenge.
        /// </summary>
        [Output("value")]
        public Output<int> Value { get; private set; } = null!;


        /// <summary>
        /// Create a ChallengeDynamicIaC resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ChallengeDynamicIaC(string name, ChallengeDynamicIaCArgs args, CustomResourceOptions? options = null)
            : base("ctfdcm:index/challengeDynamicIaC:ChallengeDynamicIaC", name, args ?? new ChallengeDynamicIaCArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ChallengeDynamicIaC(string name, Input<string> id, ChallengeDynamicIaCState? state = null, CustomResourceOptions? options = null)
            : base("ctfdcm:index/challengeDynamicIaC:ChallengeDynamicIaC", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/ctfer-io/",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ChallengeDynamicIaC resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ChallengeDynamicIaC Get(string name, Input<string> id, ChallengeDynamicIaCState? state = null, CustomResourceOptions? options = null)
        {
            return new ChallengeDynamicIaC(name, id, state, options);
        }
    }

    public sealed class ChallengeDynamicIaCArgs : global::Pulumi.ResourceArgs
    {
        [Input("additional")]
        private InputMap<string>? _additional;

        /// <summary>
        /// An optional key=value map (both strings) to pass to the scenario.
        /// </summary>
        public InputMap<string> Additional
        {
            get => _additional ?? (_additional = new InputMap<string>());
            set => _additional = value;
        }

        /// <summary>
        /// Attribution to the creator(s) of the challenge.
        /// </summary>
        [Input("attribution")]
        public Input<string>? Attribution { get; set; }

        /// <summary>
        /// Category of the challenge that CTFd groups by on the web UI.
        /// </summary>
        [Input("category", required: true)]
        public Input<string> Category { get; set; } = null!;

        /// <summary>
        /// Connection Information to connect to the challenge instance, useful for pwn, web and infrastructure pentests.
        /// </summary>
        [Input("connectionInfo")]
        public Input<string>? ConnectionInfo { get; set; }

        /// <summary>
        /// The decay defines from each number of solves does the decay function triggers until reaching minimum. This function is defined by CTFd and could be configured through `.function`.
        /// </summary>
        [Input("decay", required: true)]
        public Input<int> Decay { get; set; } = null!;

        /// <summary>
        /// Description of the challenge, consider using multiline descriptions for better style.
        /// </summary>
        [Input("description", required: true)]
        public Input<string> Description { get; set; } = null!;

        /// <summary>
        /// Whether to destroy the instance once flagged.
        /// </summary>
        [Input("destroyOnFlag")]
        public Input<bool>? DestroyOnFlag { get; set; }

        /// <summary>
        /// Decay function to define how the challenge value evolve through solves, either linear or logarithmic.
        /// </summary>
        [Input("function")]
        public Input<string>? Function { get; set; }

        /// <summary>
        /// The flag validation logic.
        /// </summary>
        [Input("logic")]
        public Input<string>? Logic { get; set; }

        /// <summary>
        /// The cost (in mana) of the challenge once an instance is deployed.
        /// </summary>
        [Input("manaCost")]
        public Input<int>? ManaCost { get; set; }

        /// <summary>
        /// The number of instances after which not to pool anymore.
        /// </summary>
        [Input("max")]
        public Input<int>? Max { get; set; }

        /// <summary>
        /// Maximum amount of attempts before being unable to flag the challenge.
        /// </summary>
        [Input("maxAttempts")]
        public Input<int>? MaxAttempts { get; set; }

        /// <summary>
        /// The minimum number of instances to set in the pool.
        /// </summary>
        [Input("min")]
        public Input<int>? Min { get; set; }

        /// <summary>
        /// The minimum points for a dynamic-score challenge to reach with the decay function. Once there, no solve could have more value.
        /// </summary>
        [Input("minimum", required: true)]
        public Input<int> Minimum { get; set; } = null!;

        /// <summary>
        /// Name of the challenge, displayed as it.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Suggestion for the end-user as next challenge to work on.
        /// </summary>
        [Input("next")]
        public Input<int>? Next { get; set; }

        /// <summary>
        /// List of required challenges that needs to get flagged before this one being accessible. Useful for skill-trees-like strategy CTF.
        /// </summary>
        [Input("requirements")]
        public Input<Inputs.ChallengeDynamicIaCRequirementsArgs>? Requirements { get; set; }

        /// <summary>
        /// The OCI reference to the scenario.
        /// </summary>
        [Input("scenario", required: true)]
        public Input<string> Scenario { get; set; } = null!;

        /// <summary>
        /// Whether the instance will be shared between all players.
        /// </summary>
        [Input("shared")]
        public Input<bool>? Shared { get; set; }

        /// <summary>
        /// State of the challenge, either hidden or visible.
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// List of challenge tags that will be displayed to the end-user. You could use them to give some quick insights of what a challenge involves.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The timeout (in seconds) after which the instance will be janitored.
        /// </summary>
        [Input("timeout")]
        public Input<int>? Timeout { get; set; }

        [Input("topics")]
        private InputList<string>? _topics;

        /// <summary>
        /// List of challenge topics that are displayed to the administrators for maintenance and planification.
        /// </summary>
        public InputList<string> Topics
        {
            get => _topics ?? (_topics = new InputList<string>());
            set => _topics = value;
        }

        /// <summary>
        /// The date until the instance could run before being janitored.
        /// </summary>
        [Input("until")]
        public Input<string>? Until { get; set; }

        /// <summary>
        /// The value (points) of the challenge once solved. It is mapped to `initial` under the hood, but displayed as `value` for consistency with the standard challenge.
        /// </summary>
        [Input("value", required: true)]
        public Input<int> Value { get; set; } = null!;

        public ChallengeDynamicIaCArgs()
        {
        }
        public static new ChallengeDynamicIaCArgs Empty => new ChallengeDynamicIaCArgs();
    }

    public sealed class ChallengeDynamicIaCState : global::Pulumi.ResourceArgs
    {
        [Input("additional")]
        private InputMap<string>? _additional;

        /// <summary>
        /// An optional key=value map (both strings) to pass to the scenario.
        /// </summary>
        public InputMap<string> Additional
        {
            get => _additional ?? (_additional = new InputMap<string>());
            set => _additional = value;
        }

        /// <summary>
        /// Attribution to the creator(s) of the challenge.
        /// </summary>
        [Input("attribution")]
        public Input<string>? Attribution { get; set; }

        /// <summary>
        /// Category of the challenge that CTFd groups by on the web UI.
        /// </summary>
        [Input("category")]
        public Input<string>? Category { get; set; }

        /// <summary>
        /// Connection Information to connect to the challenge instance, useful for pwn, web and infrastructure pentests.
        /// </summary>
        [Input("connectionInfo")]
        public Input<string>? ConnectionInfo { get; set; }

        /// <summary>
        /// The decay defines from each number of solves does the decay function triggers until reaching minimum. This function is defined by CTFd and could be configured through `.function`.
        /// </summary>
        [Input("decay")]
        public Input<int>? Decay { get; set; }

        /// <summary>
        /// Description of the challenge, consider using multiline descriptions for better style.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Whether to destroy the instance once flagged.
        /// </summary>
        [Input("destroyOnFlag")]
        public Input<bool>? DestroyOnFlag { get; set; }

        /// <summary>
        /// Decay function to define how the challenge value evolve through solves, either linear or logarithmic.
        /// </summary>
        [Input("function")]
        public Input<string>? Function { get; set; }

        /// <summary>
        /// The flag validation logic.
        /// </summary>
        [Input("logic")]
        public Input<string>? Logic { get; set; }

        /// <summary>
        /// The cost (in mana) of the challenge once an instance is deployed.
        /// </summary>
        [Input("manaCost")]
        public Input<int>? ManaCost { get; set; }

        /// <summary>
        /// The number of instances after which not to pool anymore.
        /// </summary>
        [Input("max")]
        public Input<int>? Max { get; set; }

        /// <summary>
        /// Maximum amount of attempts before being unable to flag the challenge.
        /// </summary>
        [Input("maxAttempts")]
        public Input<int>? MaxAttempts { get; set; }

        /// <summary>
        /// The minimum number of instances to set in the pool.
        /// </summary>
        [Input("min")]
        public Input<int>? Min { get; set; }

        /// <summary>
        /// The minimum points for a dynamic-score challenge to reach with the decay function. Once there, no solve could have more value.
        /// </summary>
        [Input("minimum")]
        public Input<int>? Minimum { get; set; }

        /// <summary>
        /// Name of the challenge, displayed as it.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Suggestion for the end-user as next challenge to work on.
        /// </summary>
        [Input("next")]
        public Input<int>? Next { get; set; }

        /// <summary>
        /// List of required challenges that needs to get flagged before this one being accessible. Useful for skill-trees-like strategy CTF.
        /// </summary>
        [Input("requirements")]
        public Input<Inputs.ChallengeDynamicIaCRequirementsGetArgs>? Requirements { get; set; }

        /// <summary>
        /// The OCI reference to the scenario.
        /// </summary>
        [Input("scenario")]
        public Input<string>? Scenario { get; set; }

        /// <summary>
        /// Whether the instance will be shared between all players.
        /// </summary>
        [Input("shared")]
        public Input<bool>? Shared { get; set; }

        /// <summary>
        /// State of the challenge, either hidden or visible.
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// List of challenge tags that will be displayed to the end-user. You could use them to give some quick insights of what a challenge involves.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The timeout (in seconds) after which the instance will be janitored.
        /// </summary>
        [Input("timeout")]
        public Input<int>? Timeout { get; set; }

        [Input("topics")]
        private InputList<string>? _topics;

        /// <summary>
        /// List of challenge topics that are displayed to the administrators for maintenance and planification.
        /// </summary>
        public InputList<string> Topics
        {
            get => _topics ?? (_topics = new InputList<string>());
            set => _topics = value;
        }

        /// <summary>
        /// The date until the instance could run before being janitored.
        /// </summary>
        [Input("until")]
        public Input<string>? Until { get; set; }

        /// <summary>
        /// The value (points) of the challenge once solved. It is mapped to `initial` under the hood, but displayed as `value` for consistency with the standard challenge.
        /// </summary>
        [Input("value")]
        public Input<int>? Value { get; set; }

        public ChallengeDynamicIaCState()
        {
        }
        public static new ChallengeDynamicIaCState Empty => new ChallengeDynamicIaCState();
    }
}
