// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace CTFerio.Ctfdcm
{
    public static class GetChallengesDynamiciac
    {
        public static Task<GetChallengesDynamiciacResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetChallengesDynamiciacResult>("ctfdcm:index/getChallengesDynamiciac:getChallengesDynamiciac", InvokeArgs.Empty, options.WithDefaults());

        public static Output<GetChallengesDynamiciacResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetChallengesDynamiciacResult>("ctfdcm:index/getChallengesDynamiciac:getChallengesDynamiciac", InvokeArgs.Empty, options.WithDefaults());

        public static Output<GetChallengesDynamiciacResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetChallengesDynamiciacResult>("ctfdcm:index/getChallengesDynamiciac:getChallengesDynamiciac", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetChallengesDynamiciacResult
    {
        public readonly ImmutableArray<Outputs.GetChallengesDynamiciacChallengeResult> Challenges;
        /// <summary>
        /// The ID of this resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetChallengesDynamiciacResult(
            ImmutableArray<Outputs.GetChallengesDynamiciacChallengeResult> challenges,

            string id)
        {
            Challenges = challenges;
            Id = id;
        }
    }
}
