// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getChallengesDynamiciac(opts?: pulumi.InvokeOptions): Promise<GetChallengesDynamiciacResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ctfdcm:index/getChallengesDynamiciac:getChallengesDynamiciac", {
    }, opts);
}

/**
 * A collection of values returned by getChallengesDynamiciac.
 */
export interface GetChallengesDynamiciacResult {
    readonly challenges: outputs.GetChallengesDynamiciacChallenge[];
    /**
     * The ID of this resource.
     */
    readonly id: string;
}
export function getChallengesDynamiciacOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetChallengesDynamiciacResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ctfdcm:index/getChallengesDynamiciac:getChallengesDynamiciac", {
    }, opts);
}
